### ISSUE TITLE
Getting error on using this chart

### ISSUE THREAD

**Issue by RaminderRandhawa91** [Arction/lcjs-example-0200-candlesticks#1]
I am getting error on line 
const chart = lightningChart().ChartXY({
      // Set the chart into a div with id, 'target'.
      // Chart's size will automatically adjust to div's size.
      containerId: 'target'
   })
      .setTitle('My first chart') // Set chart title

This is the error message 
Uncaught Error: EngineError: Null pointer in i
    at new i (<anonymous>:15:69454)
    at Ws (<anonymous>:15:81388)
    at i.t (<anonymous>:15:111020)
    at new i (<anonymous>:15:478664)
    at <anonymous>:61:48709
    at Object.ChartXY (<anonymous>:61:210973)
    at <anonymous>:11:35
    at b (jquery.min.js:2)
    at Ie (jquery.min.js:2)
    at k.fn.init.append (jquery.min.js:2)

**Comment by ghost** [comment]
This error comes up when you don't have a container already in the page you are trying to add the chart to.

You can add the container to the page yourself by using _document.createElement()_ for example. It should be done before adding the chart to the page.

```
// Create a container for the chart and customize it.
const flexBox = document.createElement( 'div' )
flexBox.id = 'target'
flexBox.style.position = 'relative'
flexBox.style.width = '100%'
flexBox.style.height = '800px'
flexBox.style.display = 'flex'
flexBox.style.flexDirection = 'column'
document.body.appendChild( flexBox )

// Create a XY Chart with DateTime X-axis using previously defined origin.
const chart = lightningChart().ChartXY({
    defaultAxisXTickStrategy: AxisTickStrategies.DateTime(dateOrigin),
    containerId: 'target'
})
```
